import type { ProjectsContent } from '../types';

export const projectsContent = {
  eyebrow: '',
  title: 'Projects',
  cardAriaLabel: 'Projects displayed as Memory Cards',
  memorySelect: {
    title: 'Choose a Memory Card',
    hint: 'Files are organized by status',
  },
  memoryCards: [
    {
      status: 'published',
      title: 'Completed',
      subtitle: 'Memory Card / 1',
      countLabel: '2 saved files',
    },
    {
      status: 'construction',
      title: 'In progress',
      subtitle: 'Memory Card / 2',
      countLabel: '2 saved files',
    },
  ],
  gallery: {
    eyebrow: 'Browser / Save Data',
    ariaLabel: 'Projects from the selected Memory Card',
    openLabel: 'Open project',
    backLabel: 'Change Memory Card',
  },
  memorySlot: 'Memory Card (PS2)/1',
  status: '4 professional saves — featured projects',
  saveLabel: 'Portfolio / Save Data',
  instructionsAriaLabel: 'Carousel instructions',
  instructions: ['Drag to browse', 'Select an indicator to open another save'],
  carousel: {
    ariaLabel: 'Featured projects',
    ariaRoleDescription: 'carousel',
    openLabel: 'View preview',
    indicatorLabel: 'Go to project',
  },
  dialog: {
    eyebrow: 'Project Preview',
    closeLabel: 'Close project preview',
    videoLabel: 'Video preview',
    statusLabel: 'Status',
    stackLabel: 'Technologies',
    projectAction: 'Open project',
    repositoryAction: 'Open repository',
    linksUnavailable: 'Links will be available after launch.',
    animatedPreviewLabel: 'Animated preview of project',
  },
  statusLabels: { published: 'Available', construction: 'In development' },
  projectIconLabel: '3D icon for project',
  items: [
    {
      title: 'InfoShop',
      category: 'Full-stack E-commerce',
      year: '2026',
      date: '2026-09-25',
      dateLabel: '09.25.2026',
      weight: '48 KB',
      description:
        'Computer products e-commerce platform with a public storefront, authentication, cart, checkout, shipping, and an admin dashboard.',
      stack: ['Angular', 'TypeScript', 'Supabase', 'Express'],
      id: 1,
      logo: 'infoshop',
      status: 'published',
      projectUrl: 'https://infoshop.netlify.app/',
      repositoryUrl: 'https://github.com/Gust4v0Di4sC/Info-Shop',
      previewSlug: 'infoshop',
    },
    {
      title: 'PetCorner',
      category: 'Full-stack Ecosystem',
      year: '2026',
      date: '2026-08-12',
      dateLabel: '08.12.2026',
      weight: '42 KB',
      description:
        'Pet shop ecosystem with a storefront, customer area, pet profiles, cart, checkout, orders, appointments, and an admin dashboard.',
      stack: ['Next.js', 'React', 'Firebase', 'Stripe'],
      id: 2,
      logo: 'petcorner',
      status: 'published',
      projectUrl: 'https://pet-corner-next-nine.vercel.app/',
      repositoryUrl: 'https://github.com/Gust4v0Di4sC/Pet-Corner-Next',
      previewSlug: 'pet-corner',
    },
    {
      title: 'Pizza Party',
      category: 'Full-stack Platform',
      year: '2026',
      date: '2026-09-18',
      dateLabel: '09.18.2026',
      weight: '31 KB',
      description:
        'Pizza restaurant management with an online store, orders, delivery, events, bookings, an admin area, and offline mobile support.',
      stack: ['.NET', 'ASP.NET Core', 'Angular', 'PostgreSQL', 'Ionic'],
      id: 3,
      logo: 'pizzaParty',
      status: 'construction',
    },
    {
      title: 'Theme Forge',
      category: 'Design Platform',
      year: '2026',
      date: '2026-09-04',
      dateLabel: '09.04.2026',
      weight: '27 KB',
      description:
        'Creation, preview, and export of reusable themes with light and dark modes, color palettes, typography, and multiple output formats.',
      stack: ['React', 'TypeScript', 'Chakra UI', 'NestJS', 'Prisma'],
      id: 4,
      logo: 'themeForge',
      status: 'construction',
    },
  ],
} satisfies ProjectsContent;
